export const options = [
  {
    option: "컴포트 II",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "주행안전",
  },
  {
    option: "현대스마트센스",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "주행안전",
  },
  {
    option: "주차보조 시스템",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "주행안전",
  },
  {
    option: "컴포트 I",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "주행안전",
  },
  {
    option: "2열 통풍시트",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "주행안전",
  },
  {
    option: "듀얼 와이드 선루프",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "사용편의",
  },
  {
    option: "빌트인 캠",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "사용편의",
  },
  {
    option: "듀얼 머플러 패키지",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "사용편의",
  },
  {
    option: "빌트인 공기청정기",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "추위/더위",
  },
  {
    option: "사이드 스탭 ",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "추위/더위",
  },
  {
    option: "적외선 무름워머",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "추위/더위",
  },
  {
    option: "차량 보호 필름",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "추위/더위",
  },
  {
    option: "프로텍션 매트 패키지1",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "추위/더위",
  },
  {
    option: "알콘(alcon) 단조 브레이크 & 20인치 블랙톤 전면 가공 휠 패키지",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "주차/출차",
  },
  {
    option: "디젤 2.2 엔진",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "주차/출차",
  },
  {
    option: "진동 경고 스티어링 휠",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "주차/출차",
  },
  {
    option: "8단 자동변속기",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "주차/출차",
  },
  {
    option: "차로 이탈방지 보조",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "주차/출차",
  },
  {
    option: "후진가이드램프",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "주차/출차",
  },
  {
    option: "LED 보조제동등",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "퍼포먼스",
  },
  {
    option: "싱글 트윈팁 머플러",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "스타일",
  },
  {
    option: "트윈팁 머플러(대표)",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "대표",
  },
  {
    option: "싱글  머플러(대표)",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "대표",
  },
  {
    option: "싱글 트윈팁 (대표)",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: "대표",
  },
];
