export const options = [
  {
    id:1,
    option: "컴포트 II",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: ["사용편의", "추위/더위", "스타일"],
    position: { x: 5, y: 35 },
    set:[2, 3, 4, 5, 6],
  },
  {
    id:2,
    option: "현대스마트센스",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: ["추위/더위", "주차/출차", "스타일"],
    position: { x: 20, y: 80 },
    set:null,
  },
  {
    id:3,
    option: "주차보조 시스템",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: ["주행안전", "주차/출차","추위/더위"],
    position: { x: 50, y: 10 },
    set:null,
  },
  {
    id:4,
    option: "컴포트 I",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: ["주행안전","스타일"],
    position: { x: 95, y: 85 },
    set:null,
  },
  {
    id:5,
    option: "듀얼 와이드 선루프",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: ["사용편의"],
    position: { x: 40, y: 85 },
    set:null,
  },
  {
    id:6,
    option: "빌트인 캠",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: ["사용편의"],
    position: { x: 95, y: 40 },
    set:null,
  },
  {
    id:7,
    option: "듀얼 머플러 패키지",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: ["사용편의" ],
    position: { x: 20, y: 20 },
    set:null,

  },
  {
    id:8,
    option: "빌트인 공기청정기",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: ["주행안전"],
    position: { x: 10, y: 85 },
    set:null,

  },
  {
    id:9,
    option: "적외선 무름워머",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: ["주행안전"],
    position: { x: 30, y: 55 },
    set:null,

  },
  {
    id:10,
    option: "차량 보호 필름",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: ["퍼포먼스"],
    position: { x: 60, y: 70 },
    set:null,

  },
  {
    id:11,
    option: "알콘(alcon) 단조 브레이크 & 20인치 블랙톤 전면 가공 휠 패키지",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: ["주차/출차"],
    position: { x: 90, y: 20 },
    set:null,

  },
  {
    id:12,
    option: "디젤 2.2 엔진",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: ["주차/출차"],
    position: { x: 30, y: 70 },
    set:null,

  },
  {
    id:13,
    option: "진동 경고 스티어링 휠",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: ["퍼포먼스"],
    position: { x: 70, y: 70 },
    set:null,

  },
  {
    id:14,
    option: "LED 보조제동등",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: ["퍼포먼스","추위/더위"],
    position: { x: 60, y: 70 },
    set:null,

  },
  {
    id:15,
    option: "싱글 트윈팁 머플러",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: ["스타일", "퍼포먼스"],
    position: { x: 60, y: 70 },
    set:null,

  },
  {
    id:16,
    option: "트윈팁 머플러(대표)",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: ["대표"],
    position: { x: 60, y: 70 },
    set:null,

  },
  {
    id:17,
    option: "싱글  머플러(대표)",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: ["대표"],
    position: { x: 50, y: 50 },
    set:null,

  },
  {
    id:18,
    option: "싱글 트윈팁 (대표)",
    description: "편의성을 위해 구성된 세트 옵션",
    price: "1,090,000원",
    img: "https://www.hyundai.com/contents/spec/LX24/dualwidesunroof_s.jpg",
    tag: ["대표"],
    position: { x: 30, y: 30 },
    set:null,

  },
];
